name: 'Islandora RDM Solr Config'
type: module
core_version_requirement: ^8 || ^9
dependencies:
  - block
  - block_content
  - facets
  - search_api_solr
  - media_attribution
  - vefl
package: islandora_rdm
