<?php

/**
 * @file
 * Module file.
 */
use \Drupal\block\Entity\Block;
use \Drupal\Core\Session\AccountInterface;
use \Drupal\Core\Access\AccessResult;
use \Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function islandora_rdm_theme() {
  return [
    'node__islandora_rdm_dataset__search_result' => [
      'template' => 'node--islandora-rdm-dataset--search-result',
      'preprocess functions' => ['islandora_rdm_search_result_preprocess'],
      'base hook' => 'node',
    ],
    'media__islandora_rdm_interview__teaser' => [
      'template' => 'media--islandora-rdm-interview--teaser',
      'preprocess functions' => ['islandora_rdm_interview_preprocess'],
      'base hook' => 'media',
    ],
  ];
}

/**
 * Preprocess function for search result display. Get the abstract description and put it in $variables.
 */
function islandora_rdm_search_result_preprocess(&$variables) {
  foreach ($variables['node']->get('field_rdm_description')->referencedEntities() as $description) {
    $type = $description->get('field_rdm_description_type')->getString();

    $abs_description = $description->get('field_rdm_description')->getString();
    if ($type == 'Abstract'&& trim($abs_description) != "") {
      $variables['rdm_abstract'] = "Abstract: " . $abs_description;
    }
  }
}

function islandora_rdm_preprocess_media__islandora_rdm_interview__teaser(&$variables) {
#  ksm($variables);
  $media = $variables['media'];
  $items = [];
  $captions = [];

  $recording_field = $media->get('field_interview_compressed_audio')->entity;
  if (!empty($recording_field)) {

    $items[] = file_create_url($recording_field->getFileUri());
  }
  $caption_field = $media->get('field_interview_vtt_file')->entity;
  if (!empty($caption_field)) {
    $captions_item = file_create_url($caption_field->getFileUri());
  
    $captions[] = [
      'src' => $captions_item,
      'kind' => 'captions',
      'srclang' => $media->language,
      'label' => 'Captions',
    ];
  }

  $variables['interview'] = array(
    '#theme' => 'videojs',
    '#items' => $items,
    '#captions' => $captions,
    '#player_attributes' => ['controls' => TRUE, 'width' => 500, 'height' => 400, 'poster' => base_path() . "core/themes/classy/images/icons/audio-x-generic.png"], 
    '#attached' => array(
      'library' => array('videojs/videojs'),
    ),
  );
}

/**
 * @param \Drupal\block\Entity\Block $block
 * @param $operation
 * @param \Drupal\Core\Session\AccountInterface $account
 * @return \Drupal\Core\Access\AccessResultForbidden
 */
function islandora_rdm_block_access(Block $block, $operation, AccountInterface $account) {
  if ($operation == 'view' && $block->getPluginId() == 'views_exposed_filter_block:solr_search_content-page_1'){
    $view = \Drupal::service('entity.manager')->getStorage('view')->load('solr_search_content');
    if (!$view->status()){
      return AccessResult::forbidden();
    }
  }
}
