<?php

/**
 * @file
 * Module file.
 */
use \Drupal\block\Entity\Block;
use \Drupal\Core\Session\AccountInterface;
use \Drupal\Core\Access\AccessResult;
/**
 * Implements hook_theme().
 */
function islandora_rdm_theme() {
  return [
    'node__islandora_rdm_dataset__search_result' => [
      'template' => 'node--islandora-rdm-dataset--search-result',
      'preprocess functions' => ['islandora_rdm_search_result_preprocess'],
      'base hook' => 'node',
    ],
  ];
}

/**
 * Preprocess function for search result display. Get the abstract description and put it in $variables.
 */
function islandora_rdm_search_result_preprocess(&$variables) {
  foreach ($variables['node']->get('field_rdm_description')->referencedEntities() as $description) {
    $type = $description->get('field_rdm_description_type')->getString();

    $abs_description = $description->get('field_rdm_description')->getString();
    if ($type == 'Abstract'&& trim($abs_description) != "") {
      $variables['rdm_abstract'] = "Abstract: " . $abs_description;
    }
  }
}

/**
 * @param \Drupal\block\Entity\Block $block
 * @param $operation
 * @param \Drupal\Core\Session\AccountInterface $account
 * @return \Drupal\Core\Access\AccessResultForbidden
 */
function islandora_rdm_block_access(Block $block, $operation, AccountInterface $account) {
  if ($operation == 'view' && $block->getPluginId() == 'views_exposed_filter_block:solr_search_content-page_1'){
    return AccessResult::forbidden();
  }
}
