<?php

/**
 * @file
 * Contains islandora_rdm_file_transmission_fixity.module.
 */

use Drupal\file\Entity\File;
use Drupal\media\MediaInterface;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_media_presave().
 */
function islandora_rdm_file_transmission_fixity_media_presave(MediaInterface $media) {
  $config = \Drupal::config('islandora_rdm_file_transmission_fixity.settings');
  $expected_fixity_field = $config->get('expected_fixity_field') ? $config->get('expected_fixity_field') : 'field_expected_checksum';
  $actual_fixity_field = $config->get('actual_fixity_field') ? $config->get('actual_fixity_field') : 'field_actual_checksum';
  $media_source_service = \Drupal::service('islandora.media_source_service');
  $source_field = $media_source_service->getSourceFieldName($media->bundle());
  if (empty($source_field)) {
    return;
  }
  $expected_checksum = NULL;
  if ($media->hasField($expected_fixity_field)) {
    $expected_checksum = $media->get($expected_fixity_field)->value;
  }
  $fid = $media->$source_field->target_id;
  $file = File::load($fid);
  $checksum = $file->filehash['sha1'];
  if ($media->hasField($actual_fixity_field)) {
    $media->set($actual_fixity_field, $checksum);
  }

  if ($expected_checksum) {
    if ($expected_checksum == $checksum) {
      $message = t('File checksum verified.');
      \Drupal::messenger()->addMessage($message);
    }
    else {
      $message = t('Uploaded file does not match expected checksum.');
      \Drupal::messenger()->addWarning($message);
    }
    $media->set($actual_fixity_field, "$checksum\n\n$message");
  }
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function islandora_rdm_file_transmission_fixity_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  $config = \Drupal::config('islandora_rdm_file_transmission_fixity.settings');
  $expected_fixity_field = $config->get('expected_fixity_field') ? $config->get('expected_fixity_field') : 'field_expected_checksum';
  if (isset($fields[$expected_fixity_field])) {
    $fields[$expected_fixity_field]->addConstraint('ValidSha1', []);
  }
}
