<?php

use Drupal\file\Entity\File;
use Drupal\media\MediaInterface;

/**
 * Implements hook_media_presave().
 */

function islandora_rdm_file_transmission_fixity_media_presave(MediaInterface $media) {
  $config = \Drupal::config('islandora_rdm_file_transmission_fixity.settings');
  $expected_fixity_field = $config->get('expected_fixity_field') ? $config->get('expected_fixity_field') : 'field_expected_checksum';
  $actual_fixity_field = $config->get('actual_fixity_field') ? $config->get('actual_fixity_field') : 'field_actual_checksum';
  $media_source_service = \Drupal::service('islandora.media_source_service');
  $source_field = $media_source_service->getSourceFieldName($media->bundle());
  if (empty($source_field)) {
    return;
  }
  $expected_checksum = NULL;
  if ($media->hasField($expected_fixity_field)) {
    $expected_checksum = $media->get($expected_fixity_field)->value;
  }
  $fid = $media->$source_field->target_id;
  $file = File::load($fid);
  $checksum = $file->filehash['sha1'];
  if ($media->hasField($actual_fixity_field)) {
    $media->set('field_actual_checksum', $actual_fixity_field);
  }

  if ($expected_checksum) {
    if ($expected_checksum == $checksum) {
      \Drupal::messenger()->addMessage('File checksum verified.');
    }
    else {
      \Drupal::messenger()->addWarning('Uploaded file does not match expected checksum');
    }
  }
}
