<?php

/**
 * @file
 * Module hooks.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implementation of hook_node_view_alter().
 *
 * @param array $build
 *   Entity view array.
 * @param Drupal\Core\Entity\EntityInterface $entity
 *   The entity being viewed.
 * @param Drupal\Core\Entity\Display\EntityViewDisplayInterface $display
 *   The entity display.
 */
function islandora_rdm_altmetric_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->bundle() === 'islandora_rdm_dataset') {
    if ($doi = $entity->get('field_islandora_rdm_identifier')->first()) {
      $doi_value = $doi->getValue()['value'];
      if (!empty($doi_value)) {
        $build['altmetric'] = [
          '#type' => 'markup',
          '#markup' => '<h3>Altmetric</h3>',
          '#weight' => 255,
        ];
        $build['#attached']['library'][] = 'islandora_rdm_altmetric/altmetric';
        $build['islandora_rdm_altmetric'] = [
          '#weight' => 255,
          '#type' => 'container',
          '#attributes' => [
            'class' => ['islandora-rdm-altmetric'],
          ],
          'links' => [
            '#theme' => 'item_list',
            '#attributes' => [
              'class' => ['inline'],
            ],
          ],
        ];
        $build['islandora_rdm_altmetric']['altmetric'] = [
          '#type' => 'html_tag',
          '#tag' => 'div',
          '#attributes' => [
            'class' => 'altmetric-embed',
            'data-badge-type' => 'medium-donut',
            'data-badge-details' => 'right',
            'data-condensed' => 'false',
            'data-doi' => $doi_value,
          ],
        ];
      }
    }
  }
}
